import type { ConversationScenario } from "../../types/models";

export const CONVERSATION_SCENARIOS: ConversationScenario[] = [
  {
    id: "restaurant",
    emoji: "🍕",
    title: "Ordering Food",
    titleHe: "הזמנת אוכל במסעדה",
    description: "Practice ordering a meal at a restaurant.",
    descriptionHe: "תתרגלו להזמין אוכל במסעדה.",
    aiRole: "a friendly waiter/waitress",
    studentRole: "a customer",
    grade: "both",
    starterLine: "Welcome to Sunny Café! 🍽️ Here's our menu. What would you like to order today?",
    suggestedTopics: ["food", "drinks", "prices", "recommendations"],
    followUps: [
      "Would you like something to drink with that?",
      "Do you want anything for dessert?",
      "Is this for here or to go?",
      "Would you like to hear today's specials?",
    ],
    closingLine: "Thank you for visiting! Here is your food. Enjoy your meal! 🍽️",
  },
  {
    id: "airport",
    emoji: "✈️",
    title: "At the Airport",
    titleHe: "שיחה בשדה התעופה",
    description: "Talk with airport staff about your flight and luggage.",
    descriptionHe: "שיחה עם עובד שדה תעופה לגבי הטיסה והמזוודות.",
    aiRole: "an airport check-in agent",
    studentRole: "a passenger",
    grade: "both",
    starterLine: "Good morning! Welcome to check-in. Can I see your passport and ticket, please?",
    suggestedTopics: ["travel", "luggage", "flights", "seats"],
    followUps: [
      "How many bags would you like to check in?",
      "Would you prefer a window seat or an aisle seat?",
      "Are you traveling for vacation or for something else?",
      "Do you have any liquids in your carry-on bag?",
    ],
    closingLine: "Everything looks good. Here is your boarding pass. Have a wonderful flight! ✈️",
  },
  {
    id: "hotel",
    emoji: "🏨",
    title: "Hotel Check-in",
    titleHe: "קבלה בבית מלון",
    description: "Check into a hotel and ask about the room and facilities.",
    descriptionHe: "צ'ק אין במלון ושאלות על החדר והשירותים.",
    aiRole: "a hotel receptionist",
    studentRole: "a hotel guest",
    grade: "both",
    starterLine: "Hello and welcome! Do you have a reservation with us?",
    suggestedTopics: ["rooms", "facilities", "breakfast", "wifi"],
    followUps: [
      "Would you like a room with a view of the pool or the city?",
      "What time would you like your breakfast?",
      "Do you need help carrying your luggage to the room?",
      "Is there anything special you need for your stay?",
    ],
    closingLine: "Great, you're all checked in! Here is your key. Enjoy your stay! 🏨",
  },
  {
    id: "teacher",
    emoji: "🏫",
    title: "Talking to a Teacher",
    titleHe: "שיחה עם מורה",
    description: "Practice a conversation with a teacher about school.",
    descriptionHe: "תרגול שיחה עם מורה על נושאי בית ספר.",
    aiRole: "a helpful English teacher",
    studentRole: "a student",
    grade: "both",
    starterLine: "Hi there! How is everything going with your English studies this week?",
    suggestedTopics: ["homework", "grades", "school", "help"],
    followUps: [
      "What subject do you find most difficult right now?",
      "Did you finish all of your homework this week?",
      "Is there anything I can help explain again?",
      "What's your favorite part of school these days?",
    ],
    closingLine: "Keep up the great work! I'm proud of your progress. See you next class! 🏫",
  },
  {
    id: "sports-chat",
    emoji: "⚽",
    title: "Talking About Sports",
    titleHe: "שיחה על ספורט",
    description: "Chat about your favorite sports and teams.",
    descriptionHe: "שיחה על ספורט וקבוצות אהובות.",
    aiRole: "a friend who loves sports",
    studentRole: "a friend",
    grade: "both",
    starterLine: "Hey! Did you watch the game last night? What's your favorite sport?",
    suggestedTopics: ["favorite team", "games", "players"],
    followUps: [
      "Who is your favorite player, and why?",
      "Do you play any sports yourself?",
      "What was the most exciting game you've ever watched?",
      "Do you prefer playing sports or watching them?",
    ],
    closingLine: "That was a fun chat about sports! Let's talk again soon. ⚽",
  },
  {
    id: "gaming-chat",
    emoji: "🎮",
    title: "Talking About Games",
    titleHe: "שיחה על משחקים",
    description: "Talk with a friend about your favorite video games.",
    descriptionHe: "שיחה על משחקי מחשב אהובים.",
    aiRole: "a friend who loves video games",
    studentRole: "a friend",
    grade: "both",
    starterLine: "Hey, what have you been playing lately? Any games you'd recommend?",
    suggestedTopics: ["favorite game", "consoles", "multiplayer"],
    followUps: [
      "What do you like most about that game?",
      "Do you play alone or with friends online?",
      "What's the hardest level or boss you've faced?",
      "Which game would you recommend to a beginner?",
    ],
    closingLine: "Nice talking about games with you! Good luck leveling up. 🎮",
  },
  {
    id: "shopping",
    emoji: "🛍️",
    title: "Going Shopping",
    titleHe: "קניות",
    description: "Practice shopping for clothes or gifts in a store.",
    descriptionHe: "תרגול קניות בחנות בגדים או מתנות.",
    aiRole: "a shop assistant",
    studentRole: "a shopper",
    grade: "both",
    starterLine: "Hi! Welcome to our store. Are you looking for anything special today?",
    suggestedTopics: ["clothes", "prices", "sizes", "gifts"],
    followUps: [
      "What size are you looking for?",
      "Is this a gift for someone, or for yourself?",
      "Would you like to see it in a different color?",
      "Should I check if we have that in a smaller size?",
    ],
    closingLine: "Great choice! Let's go to the register. Thanks for shopping with us! 🛍️",
  },
  {
    id: "new-friend",
    emoji: "👋",
    title: "Meeting Someone New",
    titleHe: "היכרות עם אדם חדש",
    description: "Practice introducing yourself to a new person.",
    descriptionHe: "תרגול הצגה עצמית לאדם חדש.",
    aiRole: "a new student at your school",
    studentRole: "yourself",
    grade: "both",
    starterLine: "Hi! I'm new here. What's your name?",
    suggestedTopics: ["name", "hobbies", "school", "interests"],
    followUps: [
      "What do you like to do for fun?",
      "What's your favorite class at school?",
      "Do you want to sit together at lunch?",
      "What's something interesting about you?",
    ],
    closingLine: "It was really nice meeting you! I hope we can be friends. 👋",
  },
  {
    id: "movie-chat",
    emoji: "🎬",
    title: "Talking About Movies",
    titleHe: "שיחה על סרטים",
    description: "Discuss movies you've watched recently.",
    descriptionHe: "שיחה על סרטים שראיתם לאחרונה.",
    aiRole: "a friend who loves movies",
    studentRole: "a friend",
    grade: "both",
    starterLine: "Have you seen any good movies recently? What's your favorite genre?",
    suggestedTopics: ["favorite movie", "actors", "genres"],
    followUps: [
      "Who is your favorite actor or actress?",
      "Was the ending what you expected?",
      "Would you recommend that movie to a friend?",
      "Do you prefer watching movies at home or at the cinema?",
    ],
    closingLine: "Thanks for the movie recommendations! I'll add them to my list. 🎬",
  },
  {
    id: "trip-abroad",
    emoji: "🌍",
    title: "Trip Abroad",
    titleHe: "טיול בחו\"ל",
    description: "Practice a conversation while traveling in another country.",
    descriptionHe: "תרגול שיחה בזמן טיול במדינה אחרת.",
    aiRole: "a helpful local tour guide",
    studentRole: "a tourist",
    grade: "both",
    starterLine: "Welcome! This is one of the most beautiful cities in the country. What would you like to see first?",
    suggestedTopics: ["places to visit", "directions", "culture", "food"],
    followUps: [
      "Would you like to try some traditional local food?",
      "Are you interested in museums or more outdoor activities?",
      "How many days will you be staying in the city?",
      "Would you like some tips for getting around by public transport?",
    ],
    closingLine: "I hope you have an amazing trip! Safe travels. 🌍",
  },
];
